name: Docker Image CI

permissions:
  id-token: write         # REQUIRED for OIDC
  contents: read
on:
  push:
    branches: 
      # [ "master" ]
      - dev
      - qa
      - master  
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID_DEV: 335660922529
  AWS_ACCOUNT_ID_QA: 335660922529
  AWS_ACCOUNT_ID_PROD: 335660922529
  # ECR_REPOSITORY: 335660922529.dkr.ecr.ap-south-1.amazonaws.com/fastapidevops    # â† e.g. my-app-repo
  ECR_REPOSITORY: 335660922529.dkr.ecr.us-east-1.amazonaws.com/fastapidevops
  IMAGE_NAME: fastapi-devops

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      

      - name: Determine environment from branch
        id: setenv
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          if [ "$BRANCH" = "dev" ]; then
            echo "ENV=dev" >> $GITHUB_OUTPUT
            # role ARN: either hardcode or follow naming convention
            echo "ROLE_ARN=arn:aws:iam::${{ env.AWS_ACCOUNT_ID_DEV }}:role/GitHubActions-Dev" >> $GITHUB_OUTPUT
            
          elif [ "$BRANCH" = "qa" ]; then
            echo "ENV=qa" >> $GITHUB_OUTPUT
            echo "ROLE_ARN=arn:aws:iam::${{ env.AWS_ACCOUNT_ID_QA }}:role/GitHubActions-Dev" >> $GITHUB_OUTPUT
            
          else
            echo "ENV=prod" >> $GITHUB_OUTPUT
            echo "ROLE_ARN=arn:aws:iam::${{ env.AWS_ACCOUNT_ID_PROD }}:role/GitHubActions-Dev" >> $GITHUB_OUTPUT
          fi

      - name: Print debug info
        run: |
          echo "branch: ${{ steps.setenv.outputs.branch }}"
          echo "ENV: ${{ steps.setenv.outputs.ENV }}"
          echo "ROLE_ARN: ${{ steps.setenv.outputs.ROLE_ARN }}"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "SHORT_SHA=${GITHUB_SHA::7}"

      - name: Set up QEMU (for buildx multi-arch, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login AWS
      #   run: |
      #         aws configure

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2

        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          # role-to-assume: arn:aws:iam::335660922529:role/GitHubActions-Dev
          role-to-assume: ${{ steps.setenv.outputs.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          # ${{ steps.setenv.outputs.ENV }}
      - name: Who am I (debug)
        run: aws sts get-caller-identity --output json
          

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        id: build-image
        run: |
          # IMAGE_TAG=${{ github.sha }}
          FULL_IMAGE=${{ env.ECR_REPOSITORY }}:${{env.IMAGE_NAME}}
          # build
          docker build . --file Dockerfile --tag "${FULL_IMAGE}"
          echo "full_image=${FULL_IMAGE}" >> $GITHUB_OUTPUT

      - name: Push image to ECR
        run: |
          # push the image built in the previous step
          docker push "${{ steps.build-image.outputs.full_image }}"
